name: Deploy to Prefect Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate with Prefect Cloud
      env:
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
        PREFECT_WORKSPACE_URL: ${{ secrets.PREFECT_WORKSPACE_URL }}
      run: |
        prefect cloud login -k $PREFECT_API_KEY --workspace $PREFECT_WORKSPACE_URL
        prefect config view

    - name: Deploy flow to Prefect
      run: prefect deploy -n hello-deploy
